name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  cloud-api-key:
    description: 'IBM Cloud API Key'
    required: false
    default: ''
  cloud-region:
    description: 'IBM Cloud Region'
    required: false
    default: 'us-south'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  install-ibmcloud-cli:
    description: "Installing ibmcloud cli"
    value: ${{ steps.ibm-cloud-cli.outputs }}
  login-to-ibmcloud:
    description: "Installing ibmcloud cli"
    value: ${{ steps.login-to-ibmcloud-cli.outputs }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash

    - id: ibmcloud-cli
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry
      shell: bash

    - id: login-to-ibmcloud-cli
      run: |
        ibmcloud login --apikey "${{ inputs.cloud-api-key }}" -r "${{ inputs.cloud-region }}" -g default
        ibmcloud cr region-set "${{ inputs.cloud-region }}"
        ibmcloud cr login
      shell: bash

