name: 'Hello World'
description: 'Greet someone'
inputs:
  cloud-api-key:
    description: 'IBM Cloud API Key'
    required: true
    default: ''
  cloud-region:
    description: 'IBM Cloud Region'
    required: false
    default: 'us-south'
outputs:
  install-ibmcloud-cli:
    description: "Installing ibmcloud cli"
    value: ${{ steps.ibm-cloud-cli.outputs }}
  login-to-ibmcloud:
    description: "Installing ibmcloud cli"
    value: ${{ steps.login-to-ibmcloud-cli.outputs }}
runs:
  using: "composite"
  steps:
    - id: ibmcloud-cli
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry
      shell: bash

    - id: login-to-ibmcloud-cli
      run: |
        ibmcloud login --apikey "${{ inputs.cloud-api-key }}" -r "${{ inputs.cloud-region }}" -g default
        ibmcloud cr region-set "${{ inputs.cloud-region }}"
        ibmcloud cr login
      shell: bash

